services:
  db:
    image: postgres:latest
    container_name: flights-db
    environment:
      POSTGRES_DB: Flights
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
      
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: my_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: user@domain.com
      PGADMIN_DEFAULT_PASSWORD: adminpassword
    ports:
      - "8080:80"
    depends_on:
      - db
      
  redis:
    image: redis:latest
    container_name: flights-redis
    ports:
      - "6379:6379"

volumes:
  postgres_data: