version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: flights-db
    environment:
      POSTGRES_DB: flights-test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
